### ISSUE TITLE
missing description and defaults for the HeadlessConfig properties

### ISSUE THREAD

**Issue by Techbot121** [Yellow-Dog-Man/JSONSchemas#5]
Currently only the reusable definitions have a description and defaults, but not the actual properties like `tickRate` for example.

I was going to update them manually and make a PR similarly to #4 by using the descriptions on the wiki but I think it would just get overwritten by NJsonSchema so I just created this issue instead.

**Comment by ProbablePrime** [comment]
Thank you, this was fixed in: https://github.com/Yellow-Dog-Man/JSONSchemas/commit/2253ae2f08c6f4bcc79af603a115ad08fb1e4350

where I did a complete overhaul of these schemas, try the new ones out and please give us feedback!
